-- MySQL Script generated by MySQL Workbench
-- Fri 06 Dec 2019 05:27:36 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Country` (
  `idCountry` TINYINT(4) NOT NULL,
  `hemisphere` TINYINT(4) NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`State`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`State` (
  `idState` TINYINT(4) NOT NULL,
  `idCountry` TINYINT(4) NOT NULL,
  PRIMARY KEY (`idState`),
  INDEX `fk_State_1_idx` (`idCountry` ASC),
  CONSTRAINT `fk_State_1`
    FOREIGN KEY (`idCountry`)
    REFERENCES `mydb`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Site` (
  `idSite` SMALLINT NOT NULL,
  `idState` TINYINT(4) NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`idSite`),
  INDEX `fk_State_idx` (`idState` ASC),
  CONSTRAINT `fk_State`
    FOREIGN KEY (`idState`)
    REFERENCES `mydb`.`State` (`idState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `idArea` INT NOT NULL,
  `idSite` SMALLINT NOT NULL,
  PRIMARY KEY (`idArea`),
  INDEX `fk_Site_idx` (`idSite` ASC),
  CONSTRAINT `fk_Site`
    FOREIGN KEY (`idSite`)
    REFERENCES `mydb`.`Site` (`idSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Route` (
  `idRoute` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `numPitches` TINYINT(4) NULL,
  `approach` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `idSite` SMALLINT NOT NULL,
  `idArea` INT NOT NULL,
  `difficulty` FLOAT(4,2) NULL,
  `likability` INT NULL,
  PRIMARY KEY (`idRoute`),
  INDEX `fk_Route_Area1_idx` (`idArea` ASC),
  INDEX `fk_Route_Site_idx` (`idSite` ASC),
  CONSTRAINT `fk_Route_Area1`
    FOREIGN KEY (`idArea`)
    REFERENCES `mydb`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Route_Site`
    FOREIGN KEY (`idSite`)
    REFERENCES `mydb`.`Site` (`idSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pitch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pitch` (
  `idPitch` INT NOT NULL,
  `idRoute` INT NOT NULL,
  `length` TINYINT(4) NULL,
  `difficulty` FLOAT(4,2) NULL,
  `rating` TINYINT(4) NULL,
  `pitchNum` TINYINT(4) NULL,
  PRIMARY KEY (`idPitch`),
  INDEX `fk_Route_idx` (`idRoute` ASC),
  CONSTRAINT `fk_Route`
    FOREIGN KEY (`idRoute`)
    REFERENCES `mydb`.`Route` (`idRoute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `idState` TINYINT(4) NOT NULL,
  PRIMARY KEY (`idUsers`),
  INDEX `fk_Users_State1_idx` (`idState` ASC),
  CONSTRAINT `fk_Users_State1`
    FOREIGN KEY (`idState`)
    REFERENCES `mydb`.`State` (`idState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Completed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Completed` (
  `Route_idRoute` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`Route_idRoute`, `Users_idUsers`),
  INDEX `fk_Route_has_Users_Users1_idx` (`Users_idUsers` ASC),
  INDEX `fk_Route_has_Users_Route1_idx` (`Route_idRoute` ASC),
  CONSTRAINT `fk_Route_has_Users_Route1`
    FOREIGN KEY (`Route_idRoute`)
    REFERENCES `mydb`.`Route` (`idRoute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Route_has_Users_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Route_has_Pitch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Route_has_Pitch` (
  `Pitch_idPitch` INT NOT NULL,
  `Route_idRoute` INT NOT NULL,
  PRIMARY KEY (`Pitch_idPitch`, `Route_idRoute`),
  INDEX `fk_Pitch_has_Route_Route1_idx` (`Route_idRoute` ASC),
  INDEX `fk_Pitch_has_Route_Pitch1_idx` (`Pitch_idPitch` ASC),
  CONSTRAINT `fk_Pitch_has_Route_Pitch1`
    FOREIGN KEY (`Pitch_idPitch`)
    REFERENCES `mydb`.`Pitch` (`idPitch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pitch_has_Route_Route1`
    FOREIGN KEY (`Route_idRoute`)
    REFERENCES `mydb`.`Route` (`idRoute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pictures` (
  `idPictures` INT NOT NULL,
  `pictureURL` VARCHAR(255) NULL,
  `uploadedBy` INT NULL,
  PRIMARY KEY (`idPictures`),
  INDEX `fk_UploadedBy_idx` (`uploadedBy` ASC),
  CONSTRAINT `fk_UploadedBy`
    FOREIGN KEY (`uploadedBy`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Route_has_Pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Route_has_Pictures` (
  `Route_idRoute` INT NOT NULL,
  `Pictures_idPictures` INT NOT NULL,
  PRIMARY KEY (`Route_idRoute`, `Pictures_idPictures`),
  INDEX `fk_Route_has_Pictures_Pictures1_idx` (`Pictures_idPictures` ASC),
  INDEX `fk_Route_has_Pictures_Route1_idx` (`Route_idRoute` ASC),
  CONSTRAINT `fk_Route_has_Pictures_Route1`
    FOREIGN KEY (`Route_idRoute`)
    REFERENCES `mydb`.`Route` (`idRoute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Route_has_Pictures_Pictures1`
    FOREIGN KEY (`Pictures_idPictures`)
    REFERENCES `mydb`.`Pictures` (`idPictures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
